### ISSUE TITLE
Dining Room Veranda

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#15]
![braga-back-veranda-dining-room-kitchen-first-floor-outside](https://user-images.githubusercontent.com/194400/46355343-8c6a5280-c658-11e8-946c-fae02e083deb.jpg)
![braga-back-veranda-dining-room-kitchen-first-floor-dentro](https://user-images.githubusercontent.com/194400/46355346-8c6a5280-c658-11e8-8b44-cd951fc425ee.jpg)
![braga-back-veranda-dining-room-kitchen-first-floor](https://user-images.githubusercontent.com/194400/46355348-8d02e900-c658-11e8-8897-e75627c28fdd.jpg)

@iteles iSent these to you via email so you can just forward them to the relevant people if you feel they reflect your idea for the veranda. If not, please _sit_ with me so we can re-do them. thanks.

**Comment by iteles** [comment]
It reflects it exactly. thanks.

**Comment by nelsonic** [comment]
I don't think it does. I don't think it's "right" or "perfect" at all. 
I wish you had the _time_ to sit down with me and give your _input_ ... 😞

**Comment by iteles** [comment]
When we sat down when you started drawing it, this is exactly what we discussed. I'm going to ask for a budget with this option and also with multiple panes across the front.

**Comment by nelsonic** [comment]
Inês, at _no point_ did you "sit with me" while I was drawing this. I was trying to draw it at the house and you kept _insisting_ that I walk around with Sr. Antonio to confirm the windows. you gave _exactly_ zero input on this drawing.

**Comment by iteles** [comment]
The shape is exactly what we had discussed. As I mentioned [https://github.com/dwyl/home/issues/15#issuecomment-426301666], what we discussed with Sr. António was that he would give us a budget for various window pane configurations:
+ A single non-opening pane across the front, with básculante panes on the sides
+ 2 or 3 fixed panes on the front, with básculante panes on the sides 
+ Fixed panes on the sides, with 3 basculante panes across the front
+ I will also enquire about 2 basculante panes across the front but I suspect having 2 panes only would be too big for this.

**Comment by nelsonic** [comment]
@iteles what **`else`** do you need (_from me_) in order to "make progress" with this issue?

**Comment by iteles** [comment]
Emailed earlier today. Now we wait.

**Comment by nelsonic** [comment]
@iteles do you think Carlos could get a "head start" on this?
Or is he only "keen" on working when "all the pieces" are ready?

**Comment by iteles** [comment]
Second option. Until the windows and doors are made, he won't start opening walls.

**Comment by nelsonic** [comment]
@iteles I _never **suggested**_ "opening walls". 
on the contrary, I would suggest that focusses on the _outside_ of the veranda
until the windows are made/delivered.
I can give him the design of _just_ the part he can focus on 
and then when the windows are ready, 
he just makes the "break" in the wall
cleans up the "hole" and  the windows "slot in".

**Comment by iteles** [comment]
As he's gone to another obra, he will only begin working on things when we have a solid date for the windows to arrive unfortunately 😕

**Comment by nelsonic** [comment]
@iteles can we get Carlos to "assign" a "day labourer" to our project to do "prep" tasks
so that we can make as _much_ of a "head start" as _possible_ ***`before`*** the windows/doors are ready?

**Comment by iteles** [comment]
I asked him that and he said he doesn't have enough people for the work he has on at the other sites at the moment, but to get in touch once things move forward with Sr. Antonio (who Pedro is seeing this afternoon and calling me when he's in his company).

**Comment by nelsonic** [comment]
Ok. fair enough. construction crew are "_scarce_" right now. (_we know from Andy's project_)
We could "break down" some of the tasks and create a Gantt chart in the mean time ...
good to know Pedro is visiting Sr. Antonio this afternoon. thanks.

**Comment by iteles** [comment]
We went past the factory yesterday to discuss this with the manufacturers.

Our main concern was the original cost and most importantly the _maintenance_ cost of the large window across the front.

We agreed that instead of the large front window, we would have:
+ 3 panes of glass
  + They will continue to be fixed (non-opening)
  + Preferable to 2 panes as you don't have a joint down the middle of the glass
  + If the glass is broken for some reason, a smaller pane will need to be swapped out and it can be installed manually, without the use of a crane
+ Double glazing with expansion joints between each of the 3 panes
+ Thin profile window frame around the exterior or the window
  + There was a discussion around whether having this window frame of a different thickness to all the others in the house but the concern was dismissed with more pros than cons

Note: the below is to illustrate the join between the 3 window panes _only_, the window will be straight, not curved.
![expansion-joint-window-example](https://gtaljaard.files.wordpress.com/2012/10/butt-joint-glazing2.jpg)

**Comment by nelsonic** [comment]
@iteles any news on the revised spec and cost for the veranda?

**Comment by iteles** [comment]
Still waiting. My last chase was Thursday 15th November.

**Comment by iteles** [comment]
The _frames_ for the windows arrived on 19-Dec-2018 but there was no glass in them because of a factory delay 🤦‍♀️  The glass should arrive on 4-Jan-2019 or 7-Jan-2019.

In the meantime, as we started to prepare the wall to be knocked out (by clearing the plaster first), we found this:
![img_5453](https://user-images.githubusercontent.com/4185328/50573845-99235180-0dd3-11e9-9eee-e109c50221b3.jpg)

These stones are _massive_ and easily 30-40cm in depth, much bigger than the other stone wall that has been opened up. They are much bigger than expected, will need cranes to lift them (or will all need to be sliced into smaller pieces - in itself a big job) and if one is dropped from any height, it will crash straight through the floor into the level below. Our contractor has also told us that at the level of the quote he gave us for the work, he will lose money, which is not a situation we want to put him in either.

It's a beautiful feature wall and I'm tempted to just leave it in place!

I have two major concerns with this:
+ We will lose a lot of light we had planned in this room
+ The dining room will definitely not fit the whole `home` community for a meal at once without being extended and the balcony section is thin and long and it will be tricky to use that space effectively & intuitively even if it's closed in

### Next Steps
+ [ ] Draw out the potential furniture layout for the room
+ [ ] Make a decision
+ [ ] Tell contractors

**Comment by nelsonic** [comment]
@iteles do you have time to sit with me tomorrow morning and pair on the revised veranda design?

**Comment by iteles** [comment]
Oh, I started a new sketchup document for this over the weekend but extending the original seems like a better plan:
+ **Length:** (wall along the balcony) 433cm
  + Kitchen wall to window: 130cm
  + Window width: 173cm (can be widened to bring in more light)
+ **Width:** (wall along the kitchen) 346cm
  + Co-working wall to window: 39cm
  + Window width: 172cm

**Comment by nelsonic** [comment]
@iteles please `git clone` this repo and add your sketchup file. 👍

**Comment by iteles** [comment]
@nelsonic I haven't got _very_ far as I'm still learning sketchup as I go so it'll likely be faster to just extend what there is together rather than try to retrofit one into the other 👍 Tomorrow afternoon?

**Comment by nelsonic** [comment]
Inês you "haven't got very far" ... what does that _mean_?
And _when_ is "tomorrow afternoon"?

**Comment by iteles** [comment]
Let's book a specific time on our standup tomorrow so that there is no doubt 👍

**Comment by nelsonic** [comment]
"_let's book a meeting during our meeting tomorrow_" ... 🙄

**Comment by iteles** [comment]
Fair. But it's 21h00 so it's not going to happen today and the first time we interact is our standup!

**Comment by nelsonic** [comment]
Re-worked:
![image](https://user-images.githubusercontent.com/194400/51416027-c57af400-1b6f-11e9-99ce-42baba4dc16b.png)
![image](https://user-images.githubusercontent.com/194400/51416169-3a4e2e00-1b70-11e9-9c3f-59c537c12b25.png)

**Comment by nelsonic** [comment]
@iteles I can make very workable built-in folding tables on both ends of the veranda that will maximise the space. The _original idea_ to break down the veranda walls to expand the dining room was yours, you should have the "final say" on whether the idea should be "scrapped" to make the foreman happy (_because it's going to be a **lot** of work to take down the massive stones_).
Having the opening instead of the current window will add a _lot_ of natural light.

Please make the call. 
(_I'm genuinely happy with either option. I **prefer** your idea - more open space, but I totally see Carlos' point that it's going to be a **lot** of work ... and we can always re-configure the tables in the "main" room for weekly dinners or use the "sunroom" #14 for meals_)

**Comment by nelsonic** [comment]
Exported 2D Graphics (JPG) for sharing/printing:
![braga-back-veranda-dining-room-kitchen-first-floor-revised-front](https://user-images.githubusercontent.com/194400/51423915-9dff4800-1bbe-11e9-8b56-efd9af29aff4.jpg)
![braga-back-veranda-dining-room-kitchen-first-floor-revised-front-headon](https://user-images.githubusercontent.com/194400/51423916-9dff4800-1bbe-11e9-9d83-403e39e6627b.jpg)
![braga-back-veranda-dining-room-kitchen-first-floor-revised-south-side](https://user-images.githubusercontent.com/194400/51423917-9e97de80-1bbe-11e9-8b3c-70040612ea0c.jpg)
![braga-back-veranda-dining-room-kitchen-first-floor-revised](https://user-images.githubusercontent.com/194400/51423918-9e97de80-1bbe-11e9-929b-587d954adcc0.jpg)

**Comment by nelsonic** [comment]
@iteles I printed the 2D renders.
I could not find the blu-tac/white-tac on your desk so I could not put the prints on the wall.
If you can inform me where the blu-tac/white-tac is, I will put up the prints on the wall.

**Comment by iteles** [comment]
I love this wall and having a piece of the original wall on display in `home` is an idea that makes my heart sing 🎶  But now that the construction of the _exterior_ walls has begun, the space that is left beyond the wall is _tight_ for any real seating area, even with fold-down tables. 

We had a meeting with our builders this week and agreed we would knock down the left-most wall  and not the right-most wall. The right-most wall will be cleaned up and conserved and we'll make a sunny breakfast nook behind it ☀️ 🥐 🍓

**Comment by nelsonic** [comment]
@iteles should I update the Sketchup Diagram?
Carlos was asking about (_ceiling_) _lighting_ for the veranda ... 
given that no finishing has been done yet, should we prepare a ceiling lighting plan for it?
(_to run the necessary conduit and cable ..._)

**Comment by iteles** [comment]
@nelsonic Yes, that's definitely the next step once they remake and fit the final window which they mis-measured (to keep the rain out)! 👍 
He was asking about it because I told him that was next on the list after the attic and fire safety plans when I was speaking to him and the electrician earlier this week 😉

**Comment by nelsonic** [comment]
Before: (_messy veranda with overgrown plants_)
![veranda-before](https://user-images.githubusercontent.com/194400/54067066-d4f2f100-4232-11e9-8993-912d31a2eae7.JPG)

Work-in-progress photo:
![braga-veranda-work-in-progress](https://user-images.githubusercontent.com/194400/54066840-4466e180-422f-11e9-8a97-5f4801554e5c.jpg)

**Comment by iteles** [comment]
@nelsonic I believe there are three things left to be done here:
+ [ ] Window folks need to fix the glass that has broken in the window from the fitting
+ [ ] Cementing a tiny crack in the interior (non-structural) stone wall
+ [ ] Deciding what protective coat we want on the outside of these walls

**Comment by nelsonic** [comment]
We need to take/upload updated photos next time we are at the site.

**Comment by iteles** [comment]
@nelsonic What is the best protective coat for the outside of these walls? 
Whereas the plan is to have plants everywhere #22 the growing time will mean that there is a period of time when this section of the house will look unsightly and different to the rest of the house from the outside if they leave it as-is. 

This is definitely something Carlos could work on next week.

**Comment by nelsonic** [comment]
@iteles good question. ❓ 
Currently the exterior walls are "off-white". Which I don't find visually offensive at all.
Yes it does not look amaze when contrasted with the rest of the house which is brown,
but I feel that there are much higher priority tasks for Carlos to complete that aren't painting exteriors...
The **`priority-3`** label you have applied above seems appropriate at this stage.
We can _easily_ hire someone to paint the exterior _after_ we are living in the house. 👍

**Comment by iteles** [comment]
Currently they're just 'dry cement colour', in the wet it will look dark grey.

I wasn't speaking so much of the colour as asking the question of if there's something that needs to go over the cement to protect it a bit more from the elements.

**Comment by nelsonic** [comment]
@iteles maybe get some photos tomorrow to illustrate.

**Comment by iteles** [comment]
Before the dining room extension:
![braga-pre-dining-room](https://user-images.githubusercontent.com/4185328/72687045-4a397e80-3af2-11ea-9077-1dbbf2ef3b64.JPG)

Dining room from the inside _after_ extension:
![dining-room-braga-from-inside](https://user-images.githubusercontent.com/4185328/72687051-50c7f600-3af2-11ea-9963-70dfc165d1fb.JPG)

## On the question of painting the outside (above)

This is the standard colour of the cement on the outside when dry (you can see the section colour change from the main house to the dining room extension very clearly here too):
![image](https://user-images.githubusercontent.com/4185328/72686415-6b976c00-3aec-11ea-9d7f-081c9fb7a378.png)

And then when wet - you can see the darker colour it goes when wet in the photo below, the bottom half of the wall is wet:
![image](https://user-images.githubusercontent.com/4185328/72686676-1c9f0600-3aef-11ea-97e2-117f140d9ac8.png)


:arrow_right: It needs a coat of paint so that it doesn't look disjointed and **more importantly** so that it is protected from the elements and doesn't grow moss in the next 6 months.

### The question is: what colour?

**Comment by nelsonic** [comment]
I _agree_ that the raw concrete/rendering should be protected from the elements (_moss_) ASAP. 
Please ask Carlos what his availability is to do the work. 
In the first instance I'd say we should _color-match_ it to the existing brown. 
I don't _like_ the brown and will be covering it in plants in due course.
But if the objective is _temporary_ appearance and avoidance of moss growing on it, 
then brown makes sense to "blend" it in with the rest of the building.

**Comment by nelsonic** [comment]
This turned out superbly well and is the most used room in the house especially now with desks #290 ☀️ 
Closing as complete. ✅

**Comment by iteles** [comment]
Do we *want* to protect the concrete at all?

**Comment by nelsonic** [comment]
Check it next time you're outside ... 😉
