### ISSUE TITLE
Chore: Reservar 6 Lugares de Estacionamento da Segurança Social 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#243]
@iteles spoke to Paulo Pimenta (the chap who is helping us get our concrete delivered to site) ref: https://github.com/dwyl/home/issues/242#issuecomment-1553050161 
He informed me that the _only_ way we're going to get our concrete pour for the garden 
is to use 6 parking spaces from the **Segurança Social** (behind our property) as the spot to offload the concrete. 🙄 

# Todo

+ [x] Visit the **`Segurança Social`** in-person and explain that we have no other option but to use their parking spaces for **`~3h`** and will gladly make a donation to cover the costs of their staff using alternative parking for that time.
+ [ ] Visit the Camara Municipal and find out if we can request a **`Licença para ocupação da via pública por motivo de obras`** 
https://www.cm-braga.pt/archive/doc/CMB_Reg12_CMBREG_0603_RegdeEdificacao.pdf

In both cases we are only going to say that we are having some concrete delivered to site for "obras" and no other detail.
None of them need to know _what_ "obras" and we _must_ keep our cards close to our chest as possible on this.
They don't have the right to refuse our request, they are only there to help facilitate. 

The sooner we can get this sorted the sooner we can book-in the delivery of the concrete and then work back from there to have all the formwork done in-time. 

Please LMK if you have time to get on this today or tomorrow. 🙏 
Thanks. ✨

**Comment by nelsonic** [comment]
Paulo says the best option will be to reserve the parking spaces for a morning.
e.g. by placing a few traffic cones connected with some tape and a laminated sign. 
Then remove them as soon as the truck leaves. 

> **Note**: Given that we plan to divide our work into 4 distinct "pours" we will end up needing a license for this.
So if we can get a license for a month and then only use it for the 4 mornings we require that would be awesome.
Otherwise we will have to request 4 separate days and then coordinate with Paulo to get the deliveries on those days ... 💭

**Comment by iteles** [comment]
@nelsonic I will head there tomorrow morning to ask about the parking spaces. 
What _date_ should I ask for if I can get this done right away?

**Comment by nelsonic** [comment]
@iteles Please attempt to "sweeten the deal" with Seg Soc 
by offering to pay for the parking (at the nearby private parking) 
for the 6 employees who would be inconvenienced. 💭

**Comment by iteles** [comment]
Yes, I was absolutely going to do that.

**Comment by iteles** [comment]
Put in the request for 16th June and handed in the written request. I can't add the photo of the request because it's filled with personal ID details. 

Now we wait.

**Comment by nelsonic** [comment]
@iteles did you file this request at the council (camara municipal) or SegSoc? 💭

**Comment by nelsonic** [comment]
Perfect. Thanks for doing this most tedious of chores. 🙏 
Did they give you any indication of when they were likely to respond. ⏳ 🤞

**Comment by iteles** [comment]
Unfortunately, although I asked, they couldn't give me a date. We'll go there in person to chase in a couple of weeks if we haven't heard anything.

**Comment by nelsonic** [comment]
@iteles should I call the Concrete (Cimpor) Guy and say that we have a "provisional" date or wait ... ⏳

**Comment by iteles** [comment]
Yea, I would tell him we have a provisional date though be clear we're still waiting for confirmation from the segurança social. But he needs to know that if we're going, it'll be 16th June.

**Comment by iteles** [comment]
Given the adverse weather conditions and the increased amount of work found to be needed to prep for the first pour (during the design stage), should I defer this request to the 10th July? Or later?

**Comment by iteles** [comment]
@nelsonic Yes it is. Which means the longer we take to get a new request in, the less likely we are to ever reach the top of an in tray on time. So my original request stands. 

This isn't something we can do without approval. That's reserved parking and we'll get a heavy fine.

**Comment by nelsonic** [comment]
@iteles no. I don't think you've understood. 
Please scroll up in this issue thread and search for where you ***confirmed*** that they had authorised the request. 

As far as _I_understand it, we were still "waiting" for a reply:
<img width="631" alt="home-reservar-lugares-now-we-wait" src="https://github.com/dwyl/home/assets/194400/02e97449-2e2e-4fba-b380-938daaa64879">

The status of this has not changed since you wrote that 3 weeks ago. 
Yes, you have made other comments but nothing ***confirming*** that we have authorization.
I'm not going to order €3k of concrete to be delivered if I don't have ***confirmed*** authorisation to use the space.

Maybe I wasn't clear in my original requirements. We ***MUST*** have an official piece of paper from _someone_ saying that we can use the space otherwise we ***cannot*** move forward.

**Comment by iteles** [comment]
I don't really understand what's happening here.
Obviously I'm not expecting you to have made the order already 🙃 I never even suggested that.

My last two comments have been _precisely_ to say that we never got any confirmation from them so they haven't processed the request yet. 
This means two things, which I obviously wasn't able to make clear above:
1. We need to put in a request for another date ASAP because we _know_ it takes longer than 3 weeks for them to process it _and_ we need time for them to process it and THEN place the concrete order so that date should be a month away _at least_. **To do this, I need a new date.**
2. It wouldn't be the first or the second or the third time that we get approval from a government agency the day before an event, when it is completely useless because nothing can be mobilised that fast, and only valid for 24 hours. So I was suggesting putting in the _next_ requested date _before_ tomorrow which was our original requested date, saying that we were doing so 'In light of the fact that a timely confirmation was not received from the segurança social' and preempting a possible last minute acceptance (which didn't come).

So, again, when would you like me to make the new request for, keeping in mind that it will take more than 3 weeks to get approval and that we are away for a while?

**Comment by iteles** [comment]
I spoke to a few different people on Monday (2nd October 2023) but ultimately, it was speaking to the _security guard_ that yielded the results I needed! 

Within about 10 minutes he'd managed to call down someone who could help (Pedro Nazário who apparently heads up the maintenance department or something similar - it wasn't clear).

I agreed with him that I would give him a call on the day before we needed to reserve the spots and confirm this with him. I would also email him as soon as I had a date so he could give his higher ups a heads up (which I have now done).
I offered to pay for alternative parking but he waved off the idea and said no need.

**I told him we would take care of the physical part of reserving the spots so we need to get hold of some chord or tape and something to hold it up with so that we can fence off the 6 spots the night before** @nelsonic

**Comment by nelsonic** [comment]
@iteles _how_ should we reserve the spots?
We could buy some traffic cones and tape. 
https://www.leroymerlin.pt/produtos/ferragens/seguranca-e-sinalizacao/protecao-de-garagens/cone-sinalizacao-pvc-vermelho-e-branco-50cm-14537334.html?src=clk
<img width="1431" alt="image" src="https://github.com/dwyl/home/assets/194400/7f4de77c-85ad-4ecd-9494-e54fbfde7eee">

https://www.leroymerlin.pt/produtos/ferragens/seguranca-e-sinalizacao/sinalizacao/sinalizacao/fita-sinalizadora-adesiva-50mmx33m-tesa-81958919.html
<img width="1431" alt="image" src="https://github.com/dwyl/home/assets/194400/dbbc57b8-c03c-4f75-b3cf-0f13bf3b3770">

The issue with _movable_ cones is that unless we are standing there to _stop_ people from moving them, 
the geniuses will move them and we lose the spaces and waste a mountain of cash on concrete that can't be delivered/poured. 
So, in addition to one of us standing out there waiting for the truck (Happy to volunteer with a book to read...),
I suggest that we drill into the asphalt and put 1m 10mm rods into the ground to hold the cones in place. 

Furthermore, I think we should print and laminate signs saying something like "Lugares Reservados 08:00 - 17:00" with the no Parking Sign. 

This is just illustrative:
https://www.leroymerlin.pt/produtos/ferragens/seguranca-e-sinalizacao/sinalizacao/sinalizacao/placa-de-sinalizacao-pvc-proib-estacionar-12-5x12-5cm-82598092.html?src=clk
<img width="1399" alt="image" src="https://github.com/dwyl/home/assets/194400/6029dda3-0b0c-47cc-b5e6-79b6ae4bb0c6">

If we're printing a couple of A4 signs we would just include the image on the sign and affix it to the rebar rod.

@iteles thoughts?

**Comment by iteles** [comment]
If we drill into the asphalt we may have some serious issues and not be allowed to do it again because of destruction of public property. 

I take your point on the cones but we add the segurança social logo to the print outs and head out at like 06h to make sure they're still there (before people show up to park but after the drunk people have stopped stealing cones). 

We could also park any cars available to us across the spots behind the tape to make doubly sure.

**Comment by nelsonic** [comment]
There are no "Drunk People Stealing Cones" in `PT`. That's very much a `UK` Students phenomenon. 🙃 
But I will wake up my standard "early O'Clock" (3am) and head out to place the cones.

Drilling into the asphalt is _standard_ practice for temporary works. Easy enough to re-fill:
https://www.leroymerlin.pt/produtos/construcao/recuperacao-e-escoamento-de-agua/saneamento/asfalto-em-frio-odem-20kg-82541556.html
<img width="1157" alt="image" src="https://github.com/dwyl/home/assets/194400/f70d477d-be78-4370-b96d-839fd6ac82bd">

But I take your point. 👌 
What would you suggest instead for prevent people from moving the cones?
Again, I'm happy to just sit there with my book reading for **`T90m`** (06:30 - 08:00) 

Sorry to dismiss your suggestion out-of-hand, but we aren't going to park _our_ car(s) in the spots to "reserve" them it just **looks _terrible_** ... especially given the **`type`** of car ... 🙄

**Comment by iteles** [comment]
We opted to go for the option of drilling into the asphalt and this worked well.
We also added cones to make it visually obvious and a laminated sign that said 'RESERVADO 08h00 - 13h00'

I am closing this issue.

**For the next pour we need to give Pedro Nazário at the Segurança Social about 2 weeks notice)**.

**Comment by nelsonic** [comment]
@iteles just FYI: on the morning of the pour, a lady from SegSoc approached me as I was welding saying she was the person and go authorised the parking reservation and wasn’t aware of our request. Typical of a siloed burocratic gov org where there is no clearly defined system … but just FYI. This is why we always need a paper trail. 👌

**Comment by iteles** [comment]
Yea. That was the hiccup. The top boss only came back from her holiday on Tuesday morning and she's Pedro Nazario's boss' boss. 
Pedro thought this would be a super simple approval but the day before it turned out to be a whole thing (as proven by the lady coming to speak to you) 🙄

Anyway, he managed to sort it on his end so we're all squared away 👌🏻

**Comment by nelsonic** [comment]
This went well. ✅ 
We won't be doing this again so closing. 📕 
Thanks @iteles ❤️
