### ISSUE TITLE
Shower blocked #308

### ISSUE THREAD

**Issue by MikeRund** [dwyl/home#308]
Showers not draining and leaking out of the cubicle. 

Should hopefully just be the job for a drain unblocker 
![IMG_6199](https://github.com/user-attachments/assets/e167a13d-1793-4d93-bec7-810a6b075d34)
![IMG_6200](https://github.com/user-attachments/assets/2adee70c-c308-4648-b53b-e595715d8b3b)
![IMG_6201](https://github.com/user-attachments/assets/7dd2498d-9d4d-4713-ba10-79042abc4765)

**Comment by MikeRund** [comment]
Superman swooped in 
![IMG_6202](https://github.com/user-attachments/assets/13a8a721-b49a-4962-90f2-3e10319cdec9)

**Comment by nelsonic** [comment]
@iteles this was opened by @MikeRund following a message from @davcsj ... 💬 
Given that it was causing a _flood_ each time someone showered 🤦‍♂️ 
I took action and cleaned out the clogged drain immediately. ⏳ 🚿 

But this needs to be added to the _checklist_ for regular checking and cleaning #113 
so that the overflow/flood _never_ happens again as it's a _huge_ waste of time! ⏳ 💸 🔥
